### ISSUE TITLE
question about Event-Extraction

### ISSUE THREAD

**Issue by duanshaoyang** [Keeplingshi/Event-Extraction#1]
同学你好！
       我非常想细细研读你的代码,但是我有点不太清楚这份代码的整体运行过程，你能不能给我提供一下这份代码的整体说明,这样我能细细的对照着看，希望得到你的回复，非常感谢！

**Comment by Keeplingshi** [comment]
抱歉现在才回复。因为这个代码目前还没有完成，实现还没有做完，效果并没有达到自己理想的结果。所以目前还没做说明文档。
