### ISSUE TITLE
请问一下，如何测试使用您的代码

### ISSUE THREAD

**Issue by mikeylj** [Keeplingshi/Event-Extraction#2]
我看到您的代码中，其中有一个是chinese/class_keras.py，麻烦问一下能否提供一下分类的文本。

我的QQ：54229670

谢谢！

**Comment by Keeplingshi** [comment]
这个是借用的，并不是我写的，我后来没有再用keras。原地址：https://github.com/h12345jack/nlp_hw123/tree/master/nlp_hw3/chinese
